const apartments = [
  {
    id: 1,
    name: 'The Marlstone',
    address: '5540 Spring Garden Rd',
    neighborhood: 'Spring Garden',
    rating: 5.0,
    reviewCount: 1,
    tags: ['No AI summary yet'],
    imageBg: 'linear-gradient(160deg, #7ec8a0 0%, #3a8c5e 60%, #2d6b47 100%)',
  },
  {
    id: 2,
    name: 'Park Victoria',
    address: '1496 Carlton St',
    neighborhood: 'South End',
    rating: 4.5,
    reviewCount: 2,
    tags: ['Well maintained', 'Quiet', 'Expensive'],
    imageBg: 'linear-gradient(160deg, #4a6fa5 0%, #2c4a7c 60%, #1a2f52 100%)',
  },
  {
    id: 3,
    name: 'Le Marchant Towers',
    address: '1585 Le Marchant St',
    neighborhood: 'West End',
    rating: 3.7,
    reviewCount: 3,
    tags: ['Good location', 'Parking limited', 'Aging building'],
    imageBg: 'linear-gradient(160deg, #8fa89a 0%, #5a7a6a 60%, #3d5a4c 100%)',
  },
  {
    id: 4,
    name: 'Fenwick Tower',
    address: '5599 Fenwick St',
    neighborhood: 'Downtown',
    rating: 3.3,
    reviewCount: 3,
    tags: ['Elevator issues', 'Great views', 'Security concerns'],
    imageBg: 'linear-gradient(160deg, #4a4a5a 0%, #2a2a38 60%, #1a1a25 100%)',
  },
  {
    id: 5,
    name: 'Southpoint Apartments',
    address: '1050 South Park St',
    neighborhood: 'South End',
    rating: 2.5,
    reviewCount: 4,
    tags: ['No AI summary yet'],
    imageBg: 'linear-gradient(160deg, #c07850 0%, #8a4e28 60%, #5e3018 100%)',
  },
];

export default apartments;
