const apartments = [
  {
    id: 1,
    name: 'The Marlstone',
    address: '5540 Spring Garden Rd',
    neighborhood: 'Spring Garden',
    rating: 5.0,
    reviewCount: 1,
    tags: ['No AI summary yet'],
    image: '/TheMarlstone.webp',
  },
  {
    id: 2,
    name: 'Park Victoria',
    address: '1496 Carlton St',
    neighborhood: 'South End',
    rating: 4.5,
    reviewCount: 2,
    tags: ['Well maintained', 'Quiet', 'Expensive'],
    image: '/Park Victoria.jpg',
  },
  {
    id: 3,
    name: 'Le Marchant Towers',
    address: '1585 Le Marchant St',
    neighborhood: 'West End',
    rating: 3.7,
    reviewCount: 3,
    tags: ['Good location', 'Parking limited', 'Aging building'],
    image: '/Le Marchant Towers.jpg',
  },
  {
    id: 4,
    name: 'Fenwick Tower',
    address: '5599 Fenwick St',
    neighborhood: 'Downtown',
    rating: 3.3,
    reviewCount: 3,
    tags: ['Elevator issues', 'Great views', 'Security concerns'],
    image: '/Fenwick Tower.webp',
  },
  {
    id: 5,
    name: 'Southpoint Apartments',
    address: '1050 South Park St',
    neighborhood: 'South End',
    rating: 2.5,
    reviewCount: 4,
    tags: ['No AI summary yet'],
    image: '/Southpoint Apartments.jpg',
  },
];

export default apartments;
